language: python
python: 2.7
install:
- pip install tox codecov
script:
- tox -e flake8
- tox -e isort
- tox -e py35-tests
- tox -e py27-tests
after_success:
- codecov
- git config --global user.name "semantic-release"
- git config --global user.email "semantic-release@travis"
- python setup.py install
- semantic-release publish
